### ISSUE TITLE
Can't find greple on PATH

### ISSUE THREAD

**Issue by eserte** [kaz-utashiro/greple-xp#1]
The test suite fails on some systems like this: http://www.cpantesters.org/cpan/report/c63369ea-60c3-11eb-9102-08871f24ea8f

It seems that this happens if the perl used in the tests is not the first perl in the user's `$PATH`. A fix here is not straightforward --- the test suite could add `$Config{bin}` or so to `$ENV{PATH}` before running the test cases.

**Comment by kaz-utashiro** [comment]
Thank you.  I've been thinking about how to solve this problem.
These errors are produced by this code:
```
exec $^X, "-I$lib", "-S", "greple", @_;
```
So perl executable should be fine.
Problem is the perl can't find `greple` script  in `$PATH`.
How can I know where the prerequisite script installed?

**Comment by eserte** [comment]
Maybe by doing something like this (untested): `use Config; $ENV{PATH} .= ":" . $Config{bin};` (Unix-only, MSWin32 would need a different separator).

However, this would not fix the problem if this is a smoker running in test-only mode and thus `greple` is not installed at all. In this case, one would need to use the active `$ENV{PERL5LIB}`, replace `blib/lib` by `blib/script` and look if `greple` is there, and add this path to `$ENV{PATH}`.

**Comment by kaz-utashiro** [comment]
I used $INC{"App/Greple.pm"} to get the script path and it seems to be working fine.
I appreciate your help.
